/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminLayoutRouteImport } from './routes/admin/_layout'
import { Route as UserLayoutRouteImport } from './routes/_user/_layout'
import { Route as AuthLayoutRouteImport } from './routes/_auth/_layout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminSlowPageRouteImport } from './routes/admin/slow-page'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AdminStaffsIndexRouteImport } from './routes/admin/staffs/index'
import { Route as AdminReportsIndexRouteImport } from './routes/admin/reports/index'
import { Route as UserProjectsIndexRouteImport } from './routes/_user/projects/index'
import { Route as AdminReportsIdRouteImport } from './routes/admin/reports/$id'
import { Route as AdminChatSessionIdRouteImport } from './routes/admin/chat/$sessionId'
import { Route as UserProjectsList2RouteImport } from './routes/_user/projects/list2'
import { Route as UserProjectsIdRouteImport } from './routes/_user/projects/$id'
import { Route as UserProjectsIdMembersRouteImport } from './routes/_user/projects_/$id/members'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLayoutRoute = AdminLayoutRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const UserLayoutRoute = UserLayoutRouteImport.update({
  id: '/_user',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLayoutRoute = AuthLayoutRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminSlowPageRoute = AdminSlowPageRouteImport.update({
  id: '/slow-page',
  path: '/slow-page',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AdminStaffsIndexRoute = AdminStaffsIndexRouteImport.update({
  id: '/staffs/',
  path: '/staffs/',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminReportsIndexRoute = AdminReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const UserProjectsIndexRoute = UserProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => UserLayoutRoute,
} as any)
const AdminReportsIdRoute = AdminReportsIdRouteImport.update({
  id: '/reports/$id',
  path: '/reports/$id',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminChatSessionIdRoute = AdminChatSessionIdRouteImport.update({
  id: '/chat/$sessionId',
  path: '/chat/$sessionId',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const UserProjectsList2Route = UserProjectsList2RouteImport.update({
  id: '/projects/list2',
  path: '/projects/list2',
  getParentRoute: () => UserLayoutRoute,
} as any)
const UserProjectsIdRoute = UserProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => UserLayoutRoute,
} as any)
const UserProjectsIdMembersRoute = UserProjectsIdMembersRouteImport.update({
  id: '/projects_/$id/members',
  path: '/projects/$id/members',
  getParentRoute: () => UserLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminLayoutRouteWithChildren
  '/about': typeof AboutRoute
  '/login': typeof AuthLoginRoute
  '/admin/slow-page': typeof AdminSlowPageRoute
  '/admin/': typeof AdminIndexRoute
  '/projects/$id': typeof UserProjectsIdRoute
  '/projects/list2': typeof UserProjectsList2Route
  '/admin/chat/$sessionId': typeof AdminChatSessionIdRoute
  '/admin/reports/$id': typeof AdminReportsIdRoute
  '/projects': typeof UserProjectsIndexRoute
  '/admin/reports': typeof AdminReportsIndexRoute
  '/admin/staffs': typeof AdminStaffsIndexRoute
  '/projects/$id/members': typeof UserProjectsIdMembersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof AuthLoginRoute
  '/admin/slow-page': typeof AdminSlowPageRoute
  '/admin': typeof AdminIndexRoute
  '/projects/$id': typeof UserProjectsIdRoute
  '/projects/list2': typeof UserProjectsList2Route
  '/admin/chat/$sessionId': typeof AdminChatSessionIdRoute
  '/admin/reports/$id': typeof AdminReportsIdRoute
  '/projects': typeof UserProjectsIndexRoute
  '/admin/reports': typeof AdminReportsIndexRoute
  '/admin/staffs': typeof AdminStaffsIndexRoute
  '/projects/$id/members': typeof UserProjectsIdMembersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthLayoutRouteWithChildren
  '/_user': typeof UserLayoutRouteWithChildren
  '/admin': typeof AdminLayoutRouteWithChildren
  '/about': typeof AboutRoute
  '/_auth/login': typeof AuthLoginRoute
  '/admin/slow-page': typeof AdminSlowPageRoute
  '/admin/': typeof AdminIndexRoute
  '/_user/projects/$id': typeof UserProjectsIdRoute
  '/_user/projects/list2': typeof UserProjectsList2Route
  '/admin/chat/$sessionId': typeof AdminChatSessionIdRoute
  '/admin/reports/$id': typeof AdminReportsIdRoute
  '/_user/projects/': typeof UserProjectsIndexRoute
  '/admin/reports/': typeof AdminReportsIndexRoute
  '/admin/staffs/': typeof AdminStaffsIndexRoute
  '/_user/projects_/$id/members': typeof UserProjectsIdMembersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/about'
    | '/login'
    | '/admin/slow-page'
    | '/admin/'
    | '/projects/$id'
    | '/projects/list2'
    | '/admin/chat/$sessionId'
    | '/admin/reports/$id'
    | '/projects'
    | '/admin/reports'
    | '/admin/staffs'
    | '/projects/$id/members'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/login'
    | '/admin/slow-page'
    | '/admin'
    | '/projects/$id'
    | '/projects/list2'
    | '/admin/chat/$sessionId'
    | '/admin/reports/$id'
    | '/projects'
    | '/admin/reports'
    | '/admin/staffs'
    | '/projects/$id/members'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_user'
    | '/admin'
    | '/about'
    | '/_auth/login'
    | '/admin/slow-page'
    | '/admin/'
    | '/_user/projects/$id'
    | '/_user/projects/list2'
    | '/admin/chat/$sessionId'
    | '/admin/reports/$id'
    | '/_user/projects/'
    | '/admin/reports/'
    | '/admin/staffs/'
    | '/_user/projects_/$id/members'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthLayoutRoute: typeof AuthLayoutRouteWithChildren
  UserLayoutRoute: typeof UserLayoutRouteWithChildren
  AdminLayoutRoute: typeof AdminLayoutRouteWithChildren
  AboutRoute: typeof AboutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_user': {
      id: '/_user'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof UserLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/slow-page': {
      id: '/admin/slow-page'
      path: '/slow-page'
      fullPath: '/admin/slow-page'
      preLoaderRoute: typeof AdminSlowPageRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/admin/staffs/': {
      id: '/admin/staffs/'
      path: '/staffs'
      fullPath: '/admin/staffs'
      preLoaderRoute: typeof AdminStaffsIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/reports/': {
      id: '/admin/reports/'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/_user/projects/': {
      id: '/_user/projects/'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof UserProjectsIndexRouteImport
      parentRoute: typeof UserLayoutRoute
    }
    '/admin/reports/$id': {
      id: '/admin/reports/$id'
      path: '/reports/$id'
      fullPath: '/admin/reports/$id'
      preLoaderRoute: typeof AdminReportsIdRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/chat/$sessionId': {
      id: '/admin/chat/$sessionId'
      path: '/chat/$sessionId'
      fullPath: '/admin/chat/$sessionId'
      preLoaderRoute: typeof AdminChatSessionIdRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/_user/projects/list2': {
      id: '/_user/projects/list2'
      path: '/projects/list2'
      fullPath: '/projects/list2'
      preLoaderRoute: typeof UserProjectsList2RouteImport
      parentRoute: typeof UserLayoutRoute
    }
    '/_user/projects/$id': {
      id: '/_user/projects/$id'
      path: '/projects/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof UserProjectsIdRouteImport
      parentRoute: typeof UserLayoutRoute
    }
    '/_user/projects_/$id/members': {
      id: '/_user/projects_/$id/members'
      path: '/projects/$id/members'
      fullPath: '/projects/$id/members'
      preLoaderRoute: typeof UserProjectsIdMembersRouteImport
      parentRoute: typeof UserLayoutRoute
    }
  }
}

interface AuthLayoutRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
}

const AuthLayoutRouteChildren: AuthLayoutRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
}

const AuthLayoutRouteWithChildren = AuthLayoutRoute._addFileChildren(
  AuthLayoutRouteChildren,
)

interface UserLayoutRouteChildren {
  UserProjectsIdRoute: typeof UserProjectsIdRoute
  UserProjectsList2Route: typeof UserProjectsList2Route
  UserProjectsIndexRoute: typeof UserProjectsIndexRoute
  UserProjectsIdMembersRoute: typeof UserProjectsIdMembersRoute
}

const UserLayoutRouteChildren: UserLayoutRouteChildren = {
  UserProjectsIdRoute: UserProjectsIdRoute,
  UserProjectsList2Route: UserProjectsList2Route,
  UserProjectsIndexRoute: UserProjectsIndexRoute,
  UserProjectsIdMembersRoute: UserProjectsIdMembersRoute,
}

const UserLayoutRouteWithChildren = UserLayoutRoute._addFileChildren(
  UserLayoutRouteChildren,
)

interface AdminLayoutRouteChildren {
  AdminSlowPageRoute: typeof AdminSlowPageRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminChatSessionIdRoute: typeof AdminChatSessionIdRoute
  AdminReportsIdRoute: typeof AdminReportsIdRoute
  AdminReportsIndexRoute: typeof AdminReportsIndexRoute
  AdminStaffsIndexRoute: typeof AdminStaffsIndexRoute
}

const AdminLayoutRouteChildren: AdminLayoutRouteChildren = {
  AdminSlowPageRoute: AdminSlowPageRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminChatSessionIdRoute: AdminChatSessionIdRoute,
  AdminReportsIdRoute: AdminReportsIdRoute,
  AdminReportsIndexRoute: AdminReportsIndexRoute,
  AdminStaffsIndexRoute: AdminStaffsIndexRoute,
}

const AdminLayoutRouteWithChildren = AdminLayoutRoute._addFileChildren(
  AdminLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthLayoutRoute: AuthLayoutRouteWithChildren,
  UserLayoutRoute: UserLayoutRouteWithChildren,
  AdminLayoutRoute: AdminLayoutRouteWithChildren,
  AboutRoute: AboutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
